version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
    - 4.5.0
  - dependency-name: pa11y-ci
    versions:
    - 2.4.0
